spring:
  application:
    name: prroduct.management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/product_management
    password: hanbit